#!/bin/bash
# NAME
#   new_cpp_project -- Creates a new C++ project
#
# SYNOPSIS
#   new_cpp_project ?project_name?
#
# DESCRIPTION
#   ?long description?
#
# OPTIONS
#   -1  ?description?
#
#
# ENVIRONMENT
#   The following environment variables affect the execution of name:
#   ?VAR1?  ?description?
#
# EXIT STATUS
#
# EXAMPLES
#   ?example 1? ?description?
#       ?example 1?
#
# BUGS
#   bug1
#
# Written by: Rowland O'Flaherty (rowlandoflaherty.com)
# Created on: 2014 DEC 11

project_name=$1

if [ -d $project_name ]; then
    echo ERROR: directory $project_name exist
    exit 1
fi

mkdir $project_name
cd $project_name

mkdir build
mkdir doc
mkdir include
mkdir src
mkdir dependencies
mkdir test
mkdir working

cp ~/Dropbox/Templates/cpp_project/CMakeLists_txt_root_template.txt CMakeLists.txt
sed -i "" s/___project_name___/$project_name/g CMakeLists.txt

cp ~/Dropbox/Templates/cpp_project/CMakeLists_txt_src_template.txt src/CMakeLists.txt
sed -i "" s/___project_name___/$project_name/g src/CMakeLists.txt

cp ~/Dropbox/Templates/cpp_project/CMakeLists_txt_test_template.txt test/CMakeLists.txt
sed -i "" s/___project_name___/$project_name/g test/CMakeLists.txt

cp ~/Dropbox/Templates/cpp_project/dotGitignore_template.txt .gitignore
sed -i "" s/___project_name___/$project_name/g .gitignore

cp ~/Dropbox/Templates/cpp_project/Doxyfile_template.txt Doxyfile
sed -i "" s/___project_name___/$project_name/g Doxyfile

cp ~/Dropbox/Templates/cpp_project/index_html_template.txt index.html
sed -i "" s/___project_name___/$project_name/g index.html

cp ~/Dropbox/Templates/cpp_project/LICENSE_template.txt LICENSE

cp ~/Dropbox/Templates/cpp_project/README_md_template.txt README.md
sed -i "" s/___project_name___/$project_name/g README.md

cp ~/Dropbox/Templates/cpp_project/sublime-project_template.txt $project_name.sublime-project
sed -i "" s/___project_name___/$project_name/g $project_name.sublime-project

doxygen

git init
git submodule add ssh://git@github.com/google/googletest.git dependencies/googletest
git add -A
git commit -m "Initial commit"

# git branch gh-pages

# open $project_name.sublime-project
